package httpapi

import (
	_ "embed"
	"net/http"

	"github.com/swaggest/swgui"
	"github.com/swaggest/swgui/v5emb"
)

// The specification is generated by `make swagger` from the annotations above route registrations.
var (
	//go:embed openapi/swagger.json
	openapiJSON []byte
	//go:embed openapi/swagger.yaml
	openapiYAML []byte
)

// OpenAPI returns the generated OpenAPI 2.0 specification in JSON.
func OpenAPI() []byte {
	return openapiJSON
}

// openapiRoutes serves the specification without authentication: it holds no data.
func (s *Server) openapiRoutes(mux *http.ServeMux) {
	serve := func(contentType string, spec []byte) http.HandlerFunc {
		return func(w http.ResponseWriter, _ *http.Request) {
			w.Header().Set("Content-Type", contentType)
			_, _ = w.Write(spec)
		}
	}

	//	@Summary		OpenAPI specification
	//	@Description	This specification in JSON. No authentication is required.
	//	@Tags			general
	//	@Produce		json
	//	@Success		200	{object}	object	"OpenAPI 2.0 document"
	//	@Router			/openapi.json [get]
	s.handle(mux, "GET /api/v1/openapi.json", serve("application/json", openapiJSON))

	//	@Summary		OpenAPI specification
	//	@Description	This specification in YAML. No authentication is required.
	//	@Tags			general
	//	@Produce		application/yaml
	//	@Success		200	{string}	string	"OpenAPI 2.0 document"
	//	@Router			/openapi.yaml [get]
	s.handle(mux, "GET /api/v1/openapi.yaml", serve("application/yaml", openapiYAML))
}

// swaggerUIRoutes serves Swagger UI for the embedded specification at /api/v1/docs/.
// Try it out sends requests to this server; use Authorize with "Bearer <token>".
func swaggerUIRoutes(mux *http.ServeMux) {
	ui := v5emb.NewHandlerWithConfig(swgui.Config{
		Title:       "redigate API",
		SwaggerJSON: "/api/v1/openapi.json",
		BasePath:    "/api/v1/docs/",
		SettingsUI: map[string]string{
			// 271 operations: expanded sections would be unreadable.
			"docExpansion":         `"none"`,
			"persistAuthorization": "true",
			// Request schemas carry field descriptions, show them.
			"defaultModelsExpandDepth": "1",
		},
	})

	mux.Handle("GET /api/v1/docs", http.RedirectHandler("/api/v1/docs/", http.StatusFound))
	mux.Handle("GET /api/v1/docs/", ui)
}
